# Generated by Django 3.2.6 on 2021-09-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='max',
        ),
        migrations.AddField(
            model_name='courses',
            name='seat_quota',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register',
            name='course_name',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
    ]
