# Generated by Django 3.2.6 on 2021-09-12 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_courses_remain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='remain',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='seat_quota',
        ),
    ]
