# Generated by Django 3.2.6 on 2021-09-12 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20210912_1747'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
