# Generated by Django 3.2.6 on 2021-09-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='User',
        ),
        migrations.AddField(
            model_name='student',
            name='student_courses',
            field=models.ManyToManyField(blank=True, related_name='student_courses', to='courses.Courses'),
        ),
    ]
