# Generated by Django 3.2.6 on 2021-09-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20210913_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_temp',
            field=models.ManyToManyField(blank=True, related_name='student_temp', to='courses.Courses'),
        ),
    ]
