# Generated by Django 3.2.6 on 2021-09-13 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20210914_0007'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursesInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField()),
                ('year', models.IntegerField()),
                ('courses_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.courses')),
            ],
        ),
    ]
