# Generated by Django 3.2.6 on 2021-09-13 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_coursesinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='semester',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courses',
            name='year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CoursesInfo',
        ),
    ]
