# Generated by Django 3.2.6 on 2021-09-14 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_auto_20210914_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='credit',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courses',
            name='department',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
    ]
