# Generated by Django 3.2.6 on 2021-09-14 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20210914_1818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='department',
            new_name='faculty',
        ),
    ]
