# Generated by Django 3.2.6 on 2021-09-15 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_rename_department_courses_faculty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='remain',
            new_name='n_count',
        ),
    ]
