# Generated by Django 3.2.6 on 2021-09-16 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_rename_remain_courses_n_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='n_count',
            new_name='remain',
        ),
    ]
