# Generated by Django 3.2.6 on 2021-09-16 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_rename_n_count_courses_remain'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='course_code',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
