# Generated by Django 3.2.6 on 2021-09-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_courses_course_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_lastname',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
