# Generated by Django 3.2.6 on 2021-09-17 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_student_student_lastname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_lastname',
        ),
    ]
